# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LSAT Drill Book' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LSAT Drill Book
    pod 'SwiftLint'
    pod 'VocabDict', :path => "../../../Pod\ Libraries/VocabDict/VocabDict/"

end
